import Slider from '@components/Slider';
import axios from 'axios';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Photo } from '../types';

const Home: NextPage<{ photos:Photo[]}> = ({ photos }) => {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-black text-lg">NFT</h1>


      <Slider photos={photos}/>


    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {

  const res = await axios.get(
    'https://api.pexels.com/v1/search?query=forest&per_page=8',
  );

  const results = res.data.photos;

  return{
    props: {
      photos: results
    }
  }
}

export default Home
