import axios from 'axios';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import imageLoader from '../imageLoader';
import { Photo } from '../types';

const Home: NextPage<{ photos:Photo[]}> = ({ photos }) => {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-blue-500">NFT</h1>
      {photos.map((photo) => {
        return (
          <div key={photo.id}>
            <p>{photo.photographer}</p>

            <Image
              loader={imageLoader}
              unoptimized
              src={photo.src.original}
              alt={photo.alt}
              width="200"
              height="200"
            />
          </div>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {

  const res = await axios.get(
    'https://api.pexels.com/v1/search?query=nature&per_page=3',
  );

  const results = res.data.photos;

  return{
    props: {
      photos: results
    }
  }
}

export default Home
